### ISSUE TITLE
Can I use it on GCP or Azure? 

### ISSUE THREAD

**Issue by abhinavbom** [CheckPointSW/Cuckoo-AWS#3]
Hi,
Thanks for opensourcing this. I have a few questions about the project:
1. What changes have been made over the original cuckoo code in order to make it compatible for AWS?
2. Can I also use this modified-cuckoo on Azure or GCP? If yes, do I need to made any config changes?
3. Which EC2 instance type would be best suited for running virtualbox?

**Comment by chkp-orank** [comment]
Hello @abhinavbom.
Thank you for your questions.

1.  In order to make it compatible with AWS we made the following changes.
  - Added a new machinery at cuckoo/machinery/aws.py
 -  Added a new config template at cuckoo/private/cwd/conf/aws.conf
 -  Changed the config object in a way that will support the new config (cuckoo/common/config.py)

2.  I believe that you can add a new machinery for Azure/Google based on the AWS as they all work on the same cloud principles. You will have to replace AWS API calls with Azure/google API. That will also require a similar config file.

3. VirualBox is not relevant for this project. 
I recommend you to read our blog post. It explains it in more details
https://research.checkpoint.com/cuckoo-system-on-aws/

**Comment by abhinavbom** [comment]
@chkp-orank  Thanks alot for the details. I completely missed the blog. I'll go though it and see if it answers all my questions. Thanks again!
